### ISSUE TITLE
/api/people/legislators

### ISSUE THREAD

**Issue by eflorea** [digitaldemocracy/dd-api#26]
@klau24  There are only 114 legislators - maybe this is just bad data but letting you know. 77 for assembly and 37 for senate.
![Screenshot 2023-11-07 at 5 20 18 PM](https://github.com/digitaldemocracy/dd-api/assets/13055601/60de5541-856a-47a2-8f58-c54948e027ea)
![Screenshot 2023-11-07 at 5 20 03 PM](https://github.com/digitaldemocracy/dd-api/assets/13055601/37de1f5b-1329-41c7-baee-a34e20fe0e70)

**Comment by klau24** [comment]
Thanks for the heads up. This is an issue with null values for the city value but should be fixed now.
