### ISSUE TITLE
/api/organizations

### ISSUE THREAD

**Issue by eflorea** [digitaldemocracy/dd-api#27]
@klau24 Lots of organizations seem to have like spaces and weird characters at beginning or end of the name - could we clean that up before returning the result?
![Screenshot 2023-11-07 at 5 28 27 PM](https://github.com/digitaldemocracy/dd-api/assets/13055601/dc8d17f8-b8df-43c3-aa5f-9d2757536010)

CC: @foaad

**Comment by klau24** [comment]
I am using a cleaned-up version of our orgs table. It still will not be perfect as there is an ongoing effort to deduplicate organization names.
