### ISSUE TITLE
/api/bills

### ISSUE THREAD

**Issue by eflorea** [digitaldemocracy/dd-api#28]
@klau24 The subject on some bills is null - not sure if it's intentional or just bad data.

![Screenshot 2023-11-07 at 5 32 48 PM](https://github.com/digitaldemocracy/dd-api/assets/13055601/ff0f2d08-bf65-4dba-bca0-96616aadd9e9)

CC: @foaad

**Comment by klau24** [comment]
Not all bills in the database have a subject so I have some subjects as null. Would you prefer we use something else for empty values?

**Comment by eflorea** [comment]
No I guess will stick with just the bill_number eg: "HR 1"
