### ISSUE TITLE
/api/bill votes

### ISSUE THREAD

**Issue by tobeycodes** [digitaldemocracy/dd-api#86]
For each vote we need a list of the votees. These should be grouped by ayes, abstains, and naes. We need the image, first, last and party for each vote.

http://44.240.238.232:8080/api/bill/CA_201720180AB10

**Comment by klau24** [comment]
For each vote summary, you also want the voting breakdown correct? Something like this:

```
votes: [
{
   abstain: 5,
   ayes: 70,
   date: "2017-09-11",
   naes: 4,
   result: "(PASS)",
   text: "AB 10 GARCIA, C. Concurrence in Senate Amendments",
   vote_detail: [
      {
         data: [
            {
               image: ...,
               first: ...,
               last: ...,
               party: ...
            }
         ]
         vote_group: "ayes"
      },
      {
         data: [
            {
               image: ...,
               first: ...,
               last: ...,
               party: ...
            }
         ]
         vote_group: "naes"
      },
      {
         data: [
            {
               image: ...,
               first: ...,
               last: ...,
               party: ...
            }
         ]
         vote_group: "abstain"
      }
   ]
},
...
]
```

**Comment by tobeycodes** [comment]
Yes. I think vote_detail can either be an array of votes where each vote has a property of what their vote was or vote_detail can be an object of ayes, naes and abstain. 

The example you have will work but it is quite verbose

**Comment by klau24** [comment]
Ok, I went with an array of votes with a `result` field that can be one of the following values: `AYE`, `NOE`, and `ABS`. Let me know if the format needs to be changed.
